[project]
name = "isa_worker"
version = "0.1.0"
description = "Aplikacja ISA worker, która odlicza sekundy"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.124.2",
    "fastapi-cli>=0.0.16",
    "redis==7.0.0",
]

[dependency-groups]
dev = [
    "pytest>=9.0.2",
    "ruff>=0.14.8",
]

[project.scripts]
isa_worker = "isa_worker.__main__:main"
